Upgraded the SER version from 0.10.99-dev53 to 2.1.0-dev1 (Ottendorf)
- the CVS version of SER that this was synchronized with can be found in ser_ims/sip_router/CVS_2007.03.02_16:09:34

diff --git a/ser_ims/trunk/Makefile b/ser_ims/trunk/Makefile
--- a/ser_ims/trunk/Makefile
+++ b/ser_ims/trunk/Makefile
@@ -11,7 +11,7 @@
 #              created by andrei
 #  2003-02-24  make install no longer overwrites ser.cfg  - patch provided
 #               by Maxim Sobolev   <sobomax@FreeBSD.org> and 
-#                  Tomas Bj??rklund <tomas@webservices.se>
+#                  Tomas Björklund <tomas@webservices.se>
 #  2003-03-11  PREFIX & LOCALBASE must also be exported (andrei)
 #  2003-04-07  hacked to work with solaris install (andrei)
 #  2003-04-17  exclude modules overwritable from env. or cmd. line,
@@ -32,13 +32,25 @@
 #  2006-02-14  added utils & install-utils (andrei)
 #  2006-03-15  added nodeb parameter for make tar (andrei)
 #  2006-09-29  added modules-doc as target and doc_format= as make option (greger)
-#
+#  2006-12-09  added new group_include as make option and defined groups 
+#               defining which modules to include. Also added new target 
+#               print-modules that you can use to check which modules will be 
+#               compiled (greger)
+#  2007-01-10  added new group_include targets mysql, radius, and presence 
+#               improved print-modules output fixed problem in include/exclude
+#               logic when using group_include (greger)
+#  2007-03-01  fail if a module or a required utility make fail unless 
+#              err_fail=0; don't try to make modules with no Makefiles (andrei)
 
 auto_gen=lex.yy.c cfg.tab.c #lexx, yacc etc
 auto_gen_others=cfg.tab.h  # auto generated, non-c
 
 #include  source related defs
 include Makefile.sources
+
+# whether or not the entire build process should fail if building a module or
+#  an utility fails
+err_fail?=1
 
 # whether or not to install ser.cfg or just ser.cfg.default
 # (ser.cfg will never be overwritten by make install, this is usefull
@@ -52,8 +64,68 @@ skip_modules?=
 # Alternatives are txt, html, xhtml, and pdf (see Makefile.doc)
 doc_format?=html
 
-# if not set on the cmd. line or the env, exclude this modules:
-exclude_modules?= 			acc cpl ext extcmd radius_acc radius_auth vm\
+# Module group definitions, default only include the standard group
+# Make backwards compatible, don't set group_include default...
+#group_include?="standard"
+
+# Modules in this group are considered a standard part of SER (due to 
+# widespread usage) and have no external compile or link dependencies (note 
+# that some of these interplay with external systems).
+module_group_standard=acc_syslog auth avp avpops ctl dispatcher diversion enum\
+				eval exec fifo flatstore gflags maxfwd mediaproxy \
+				nathelper options pdt permissions pike print ratelimit \
+				registrar rr sanity sl textops timer tm uac unixsock uri \
+				usrloc xlog
+
+# Modules in this group are considered a standard part of SER (due to 
+# widespread usage) but they have dependencies that must be satisfied for 
+# compilation.
+# acc_radius, auth_radius, avp_radius, uri_radius => radiusclient-ng
+# acc_db, auth_db, avp_db, db_ops, domain, lcr, msilo, dialog, speeddial,
+# uri_db => database module (mysql, postgres, dbtext)
+# mysql, postgres => mysql server and client libraries or postgres server and
+#  client libraries or other database back-end (ex. mysql-devel)
+# pa, xmlrpc => libxml2
+# rls => pa
+#
+# NOTE! All presence modules (dialog, pa, presence_b2b, rls, xcap) have been
+# included in this group due to interdependencies
+module_group_standard_dep=acc_db acc_radius auth_db auth_radius avp_db \
+				avp_radius \
+				db_ops domain lcr msilo mysql dialog pa postgres \
+				presence_b2b rls speeddial uri_db xcap xmlrpc
+
+# For mysql
+module_group_mysql=acc_db auth_db avp_db db_ops uri_db domain lcr msilo mysql\
+				speeddial
+
+# For radius
+module_group_radius=acc_radius auth_radius avp_radius
+
+# For presence
+module_group_presence=dialog pa presence_b2b rls xcap
+
+# Modules in this group satisfy specific or niche applications, but are 
+# considered stable for production use. They may or may not have dependencies
+# cpl-c => libxml2
+# jabber => expat (library)
+# osp => OSP Toolkit (sipfoundry)
+# sms => none (external modem)
+module_group_stable=cpl-c dbtext jabber osp sms
+
+# Modules in this group are either not complete, untested, or without enough
+# reports of usage to allow the module into the stable group. They may or may
+# not have dependencies
+module_group_experimental=tls oracle
+
+# if not set on the cmd. line or the env, exclude the below modules.
+ifneq ($(group_include),)
+	# For group_include, default all modules are excluded except those in 
+	# include_modules
+	exclude_modules?=
+else
+	# Old defaults for backwards compatibility
+	exclude_modules?= 			acc cpl ext extcmd radius_acc radius_auth vm\
 							group mangler auth_diameter \
 							postgres snmp \
 							im \
@@ -61,13 +133,41 @@ exclude_modules?= 			acc cpl ext extcmd radius_acc radius_auth vm\
 							cpl-c \
 							auth_radius group_radius uri_radius avp_radius \
 							acc_radius pa rls presence_b2b xcap xmlrpc\
-							osp tls \
-							unixsock eval
+							osp tls oracle \
+							unixsock eval dbg
+endif
+
 # always exclude the CVS dir
 override exclude_modules+= CVS $(skip_modules)
 
-#always include this modules
-include_modules?=
+# Test for the groups and add to include_modules
+ifneq (,$(findstring standard,$(group_include)))
+	override include_modules+= $(module_group_standard)
+endif
+
+ifneq (,$(findstring standard-dep,$(group_include)))
+	override include_modules+= $(module_group_standard_dep)
+endif
+
+ifneq (,$(findstring mysql,$(group_include)))
+	override include_modules+= $(module_group_mysql)
+endif
+
+ifneq (,$(findstring radius,$(group_include)))
+	override include_modules+= $(module_group_radius)
+endif
+
+ifneq (,$(findstring presence,$(group_include)))
+	override include_modules+= $(module_group_presence)
+endif
+
+ifneq (,$(findstring stable,$(group_include)))
+	override include_modules+= $(module_group_stable)
+endif
+
+ifneq (,$(findstring experimental,$(group_include)))
+	override include_modules+= $(module_group_experimental)
+endif
 
 # first 2 lines are excluded because of the experimental or incomplete
 # status of the modules
@@ -84,11 +184,22 @@ static_defs= $(foreach  mod, $(static_modules), \
 override extra_defs+=$(static_defs) $(EXTRA_DEFS)
 export extra_defs
 
-modules=$(filter-out $(addprefix modules/, \
+# Historically, the resultant set of modules is: modules/* - exclude_modules +
+# include_modules
+# When group_include is used, we want: include_modules (based on group_include)
+# - exclude_modules
+ifneq ($(group_include),)
+	modules=$(filter-out $(addprefix modules/, \
+			$(exclude_modules) $(static_modules)), \
+			$(addprefix modules/, $(include_modules) ))
+else	
+	# Standard, old resultant set
+	modules=$(filter-out $(addprefix modules/, \
 			$(exclude_modules) $(static_modules)), \
 			$(wildcard modules/*))
-modules:=$(filter-out $(modules), $(addprefix modules/, $(include_modules) )) \
+	modules:=$(filter-out $(modules), $(addprefix modules/, $(include_modules) )) \
 			$(modules)
+endif
 modules_names=$(shell echo $(modules)| \
 				sed -e 's/modules\/\([^/ ]*\)\/*/\1.so/g' )
 modules_basenames=$(shell echo $(modules)| \
@@ -116,7 +227,8 @@ include Makefile.defs
 NAME=$(MAIN_NAME)
 
 #export relevant variables to the sub-makes
-export DEFS PROFILE CC LD MKDEP MKTAGS CFLAGS LDFLAGS INCLUDES MOD_CFLAGS MOD_LDFLAGS 
+export DEFS PROFILE CC LD MKDEP MKTAGS CFLAGS LDFLAGS INCLUDES MOD_CFLAGS \
+		MOD_LDFLAGS 
 export LIBS
 export LEX YACC YACC_FLAGS
 export PREFIX LOCALBASE
@@ -135,16 +247,22 @@ tar_name=$(NAME)-$(RELEASE)_src
 
 tar_extra_args+=$(addprefix --exclude=$(notdir $(CURDIR))/, \
 					$(auto_gen) $(auto_gen_others))
-ifneq ($(TLS),)
+ifeq ($(CORE_TLS), 1)
 	tar_extra_args+=
 else
-	tar_extra_args+=--exclude=$(notdir $(CURDIR))/tls* 
+	tar_extra_args+=--exclude=$(notdir $(CURDIR))/tls/* 
 endif
 
 ifneq ($(nodeb),)
 	tar_extra_args+=--exclude=$(notdir $(CURDIR))/debian 
 	tar_name:=$(tar_name)_nodeb
 endif
+
+# sanity checks
+ifneq ($(TLS),)
+	$(warning "make TLS option is obsoleted, try TLS_HOOKS or CORE_TLS")
+endif
+
 # include the common rules
 include Makefile.rules
 
@@ -161,37 +279,49 @@ cfg.tab.c cfg.tab.h: cfg.y  $(ALLDEP)
 .PHONY: all
 all: $(NAME) modules
 
-
+.PHONY: print-modules
+print-modules:
+	@echo The following modules was chosen to be included: $(include_modules) ; \
+	echo ---------------------------------------------------------- ; \
+	echo The following modules will be excluded: $(exclude_modules) ; \
+	echo ---------------------------------------------------------- ; \
+	echo The following modules will be made: $(modules_basenames) ; \
 
 .PHONY: modules
 modules:
-	-@for r in $(modules) "" ; do \
-		if [ -n "$$r" ]; then \
+	@for r in $(modules) "" ; do \
+		if [ -n "$$r" -a -r "$$r/Makefile" ]; then \
 			echo  "" ; \
 			echo  "" ; \
-			$(MAKE) -C $$r ; \
+			if ! $(MAKE) -C $$r && [ ${err_fail} = 1 ] ; then \
+				exit 1; \
+			fi ; \
 		fi ; \
-	done 
+	done; true
 
 $(extra_objs):
-	-@echo "Extra objs: $(extra_objs)" 
-	-@for r in $(static_modules_path) "" ; do \
-		if [ -n "$$r" ]; then \
+	@echo "Extra objs: $(extra_objs)" 
+	@for r in $(static_modules_path) "" ; do \
+		if [ -n "$$r" -a -r "$$r/Makefile"  ]; then \
 			echo  "" ; \
 			echo  "Making static module $r" ; \
-			$(MAKE) -C $$r static ; \
+			if ! $(MAKE) -C $$r static ; then  \
+				exit 1; \
+			fi ;  \
 		fi ; \
-	done 
+	done
 
 .PHONY: utils
 utils:
-	-@for r in $(utils_compile) "" ; do \
+	@for r in $(utils_compile) "" ; do \
 		if [ -n "$$r" ]; then \
 			echo  "" ; \
 			echo  "" ; \
-			$(MAKE) -C $$r ; \
+			if ! $(MAKE) -C $$r && [ ${err_fail} = 1 ] ; then \
+				exit 1; \
+			fi ; \
 		fi ; \
-	done 
+	done; true
 
 
 dbg: ser
@@ -331,7 +461,7 @@ install-bin: $(bin-prefix)/$(bin-dir)
 		$(INSTALL-BIN) ser $(bin-prefix)/$(bin-dir)
 
 install-modules: modules $(modules-prefix)/$(modules-dir)
-	-@for r in $(modules_full_path) "" ; do \
+	@for r in $(modules_full_path) "" ; do \
 		if [ -n "$$r" ]; then \
 			if [ -f "$$r" ]; then \
 				$(INSTALL-TOUCH) \
@@ -339,12 +469,15 @@ install-modules: modules $(modules-prefix)/$(modules-dir)
 				$(INSTALL-MODULES)  "$$r"  $(modules-prefix)/$(modules-dir) ; \
 			else \
 				echo "ERROR: module $$r not compiled" ; \
+				if [ ${err_fail} = 1 ] ; then \
+					exit 1; \
+				fi ; \
 			fi ;\
 		fi ; \
-	done 
+	done; true
 
 install-utils: utils $(bin-prefix)/$(bin-dir)
-	-@for r in $(utils_install) "" ; do \
+	@for r in $(utils_install) "" ; do \
 		if [ -n "$$r" ]; then \
 			if [ -f "$$r" ]; then \
 				$(INSTALL-TOUCH) \
@@ -352,9 +485,12 @@ install-utils: utils $(bin-prefix)/$(bin-dir)
 				$(INSTALL-BIN)  "$$r"  $(bin-prefix)/$(bin-dir) ; \
 			else \
 				echo "ERROR: $$r not compiled" ; \
+				if [ ${err_fail} = 1 ] ; then \
+					exit 1; \
+				fi ; \
 			fi ;\
 		fi ; \
-	done 
+	done; true
 
 
 
@@ -375,7 +511,7 @@ install-doc: $(doc-prefix)/$(doc-dir) install-modules-doc
 
 
 install-modules-doc: $(doc-prefix)/$(doc-dir)
-	-@for r in $(modules_basenames) "" ; do \
+	@for r in $(modules_basenames) "" ; do \
 		if [ -n "$$r" ]; then \
 			if [ -f modules/"$$r"/README ]; then \
 				$(INSTALL-TOUCH)  $(doc-prefix)/$(doc-dir)/README ; \
@@ -401,3 +537,48 @@ install-man: $(man-prefix)/$(man-dir)/man8 $(man-prefix)/$(man-dir)/man5
 			-e "s#/usr/share/doc/ser/#$(doc-target)#g" \
 			< ser.cfg.5 >  $(man-prefix)/$(man-dir)/man5/ser.cfg.5
 		chmod 644  $(man-prefix)/$(man-dir)/man5/ser.cfg.5
+
+
+##################
+# making libraries
+# 
+# you can use:
+#    make libs all include_modules=... install prefix=...
+#    make libs proper
+#
+# but libs should be compiled/installed automaticaly when there are any modules which need them
+
+lib_dependent_modules = dialog pa rls presence_b2b xcap
+
+# exports for libs
+export cfg-prefix cfg-dir bin-prefix bin-dir modules-prefix modules-dir
+export doc-prefix doc-dir man-prefix man-dir ut-prefix ut-dir
+export INSTALL INSTALL-CFG INSTALL-BIN INSTALL-MODULES INSTALL-DOC INSTALL-MAN 
+export INSTALL-TOUCH
+
+dep_mods = $(filter $(addprefix modules/, $(lib_dependent_modules)), $(modules))
+dep_mods += $(filter $(lib_dependent_modules), $(static_modules))
+
+# make 'modules' dependent on libraries if there are modules which need them 
+# (experimental)
+ifneq ($(strip $(dep_mods)),)
+modules:	libs
+
+install-modules:	install-libs
+
+endif
+
+.PHONY: clean_libs libs install-libs
+
+clean_libs:
+			$(MAKE) -f Makefile.ser -C lib proper
+
+# cleaning in libs always when cleaning ser
+clean:	clean_libs
+
+libs:	
+		$(MAKE) -C lib -f Makefile.ser
+
+install-libs:	
+		$(MAKE) -C lib -f Makefile.ser install
+
